### ISSUE TITLE
Integration mit PhoneBlock

### ISSUE THREAD

**Issue by haumacher** [blacksenator/fbcallrouter#10]
Ich habe vor einiger Zeit das Projekt PhoneBlock (https://github.com/haumacher/phoneblock) gestartet, dass eine Sperrliste als Internet-Adressbuch für die Fritz!Box zur Verfügung stellt. Man kann das PhoneBlock-Adressbuch in der Fritz!Box einrichten und dort alle Anrufe von der Blocklist automatisch abweisen lassen (live auszuprobieren hier: https://phoneblock.haumacher.de/). Der Vorteil ist, dass man keine Zusatzhardware benötigt. Der Nachteil ist aber, dass PhoneBlock keine Rückmeldung erhält, wenn Spam-Anrufe weggefiltert werden. Daher ist es schwer zu sagen, ob eine Spam-Nummer noch aktiv ist. Da ein Adresssbuch in der Fritz!Box nur begrenzt viele Nummer aufnehmen kann, muss man aber immer wieder Nummer von der Blocklist streichen.

Wenn ich das richtig verstanden habe, dann beobachtet fbcallrouter aktiv die Anrufe in der Fritz!Box und könnte der Datenbank mit Spam-Nummer eine Rückmeldung geben, dass ein Anruf weggefiltert worden ist. Ich würde gerne eine (einfache) Schnittstelle bereitstellen, mit der fbcallrouter die Blocklist von PhoneBlock abrufen/synchronisieren kann - im Gegenzug könnte fbcallrouter PhoneBlock mit Informationen versorgen, wenn ein Anruf tatsächlich blockiert wurde.

Kannst Du sagen, wieviele Installationen es von fbcallrouter gibt?

**Comment by blacksenator** [comment]
Hallo Bernhard,
bitte kontaktiere mich direkt per E-Mail. Adresse findest Du im Coding der Klassen.
Volker

**Comment by haumacher** [comment]
PhoneBlock hätte jetzt eine API, mit der man eine Integration machen könnte: https://phoneblock.haumacher.de/phoneblock/api/

Ticket https://github.com/haumacher/phoneblock/issues/10
