### ISSUE TITLE
Feature Request: Auch bei positiven Bewertungen die Rückwärtssuche starten, wenn newlist aktiv

### ISSUE THREAD

**Issue by binderth** [blacksenator/fbcallrouter#13]
Ich habe gerade den Fall, dass eine unbekannte Telefonnummer angerufen hat:
1. Rating 5 bei 0 Kommentaren bei tellows
2. Der Anruf wurde angenommen
3. keine weitere Prüfung

In diesem Fall hätte ich aber gerne die Telefonnummer in dem von mir angegebenen "Newlist"-Telefonbuch bekommen, d.h. 
1. Rating 5 bei 0 Kommentaren bei tellows
2. Der Anruf wurde angenommen
3. **weitere Prüfung: Ist die Telefonnummer in der Rückwärtssuche enthalten**
4. **wenn Telefonnummer gefunden wird: Eintrag in newlist**

Damit wäre die Telefonnummer mit gefundenem Namen dann auch im Display bei (künftigen?) Anrufen - und muss nicht mehr geprüft werden, wenn das newlist-Telefonbuch in der Whitelist-Liste aufgeführt ist.

**Comment by blacksenator** [comment]
implemented
