### ISSUE TITLE
fbcallrouter startet nicht

### ISSUE THREAD

**Issue by vopi61** [blacksenator/fbcallrouter#14]
Hallo blacksenator (Sorry for writing in german),
habe deine Installationsanleitung Punkt für Punkt befolgt. Leider startet das Programm nicht. Nach Eingabe von: "php fbcallrouter run" kommt immer: 

I followed your installation guide step by step. Unfortunately the program does not start. After entering: "php fbcallrouter run" always shows up:

PHP Fatal error:  Uncaught Error: Call to a member function GetPhonebookList() on null in /home/vopi/fbcallrouter/vendor/blacksenator/fritzsoap/src/x_contact.php:253

Stack trace:
#0 /home/vopi/fbcallrouter/src/callrouter/phonetools.php(77): blacksenator\fritzsoap\x_contact->getPhonebookList()
#1 /home/vopi/fbcallrouter/src/callrouter/phonetools.php(63): blacksenator\callrouter\phonetools->getPhoneBookList()
#2 /home/vopi/fbcallrouter/src/callrouter/callrouter.php(75): blacksenator\callrouter\phonetools->__construct(Array)
#3 /home/vopi/fbcallrouter/src/functions.php(16): blacksenator\callrouter\callrouter->__construct(Array, Array)
#4 /home/vopi/fbcallrouter/src/RunCommand.php(32): blacksenator\callRouting(Array, Array)
#5 /home/vopi/fbcallrouter/vendor/symfony/console/Command/Command.php(255): blacksenator\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/vopi/fbcallrouter/vendor/symfony/console/Application.php(992): Symfony\Component\Consol in /home/vopi/fbcallrouter/vendor/blacksenator/fritzsoap/src/x_contact.php on line 253

kannst du weiterhelfen?

Gruß Stefan

**Comment by blacksenator** [comment]
Hallo Stefan,

der Fehler tritt bei der Initialisierung auf. Mit `x_contact->getPhonebookList()` werden alle aktuell auf der FRITZ!Box verfügbaren Telefonbuch-Indices eingelesen, um zu prüfen, ob z.b. der Index des Spam-Telefonbuchs überhaupt valide ist.
Da es sich um eine SOAP- bzw- TR-064-Routine handelt, vermute ich, dass der verwendete User nicht über die [notwendigen Rechte](https://github.com/blacksenator/fbcallrouter#fritzbox-user) verfügt.
Minimal muss der User berechtigt sein für:
- Sprachnachrichten, Faxnachrichten, FRITZ!App Fon und Anrufliste

Der von mir "empfohlene" User `dslf_config` - das habe ich gerade getestet - funktioniert (anders als früher) nicht mehr. Ich passe die README kurzfristig an.

Beste Grüße

Black Senator

**Comment by vopi61** [comment]
guten Abend,
ich habe in die config.php als user: Boxadmin eingetragen mit dem entsprechenden PW. Außerdem ist callmonitor offen. Spamtelefonbuch ist auch angelegt (2ter Tab also mit 1 eingetragen in config.php), whitelist ist 3ter Tab also mit 2 eingetragen in config.php.

![Rechte](https://user-images.githubusercontent.com/7520390/223551274-1b24afb3-9101-4916-af76-45b9f45b1cf9.png)

**Comment by blacksenator** [comment]
Hmmm, dann wirds schwierig, Dann kann es an allem möglichen liegen.
Du findest meine Adresse im Coding: am besten schreibst Du mich mal PM an und wir verlagern die Konversation dahin.

**Comment by vopi61** [comment]
weiß nicht wo ich deine mail-adresse finden kann. Was meinst du mit Coding? Sorry :)

**Comment by blacksenator** [comment]
steht u.a. in der fritzsoap.php

**Comment by blacksenator** [comment]
@vopi61 thanks for your patience and testing. We found out that the notes on the PHP version and the version information for Composer were no longer up to date and could cause incompatibilities. Fixed!
