### ISSUE TITLE
[Feature request] Add link for searchresult for good numbers

### ISSUE THREAD

**Issue by MegaV0lt** [blacksenator/fbcallrouter#18]
```
The following results and actions have been recorded:

08.08.2023 15:02:15 => CALL IN from number 0404223602692 to MSN 471033

08.08.2023 15:02:18 => Caller has a rating of 9 out of 9 and 2 valuations.
```
I miss the link to the search in the web, where i can check the number.

**Comment by blacksenator** [comment]
Since the various telephone book databases are queried sequentially, it cannot be decided in which of the databases the entry with the same neutral values was found. For this reason, no database is specified in these cases.
