### ISSUE TITLE
feature request: Führende Zahlen, die automatisch im SPAM landen

### ISSUE THREAD

**Issue by binderth** [blacksenator/fbcallrouter#22]
Ich habe festgestellt, dass ich erstaunlich viele SPAM-Anrufe erhalte, die immer dieselbe Vorwahl tragen:
* **01521** 4094105
* **01521** 7871549
* **01521** 0467468
* **01521** 7595144

...

Auch auf die Gefahr ein paar false negative zu erhalten: wäre es sinnvoll, den Filter um solche "Vorwahlen" zu ergänzen? 
Bei mir laufen alle SPAM-Anrufe sofort auf einen eigenen SPAM-Anrufbeantworter auf dem ich erkläre, der Anruf ist im SPAM-Filter gelandet und wer meint, das sei falsch, solle drauf sprechen. Ich habe bisher nur vier AB-Nachrichten von drölfzig solchen Anrufen erhalten. Alle waren automatische Bandansagen der üblichen "Sie haben gewonnen, drücken sie 1"... Masche. von daher können da gern die false positiven draufsprechen, dass sie mich sprechen wollen.

**Comment by blacksenator** [comment]
Hallo Thomas,

das möchte ich nicht fix mit einprogrammieren. Zumal es m.N.n. eine bessere und effektivere Lösung gibt: du kannst doch die Vorwahl 01521* komplett direkt in der Fritzbox per Rufbehandlung abweisen, bzw. auf einen AB umleiten. Der Umweg in den fbcallrouter ist da m.E. nicht sinnvoll, denn damit sollen ja solche Anrufer identifiziert werden, die nicht so einfachen Mustern zuzuordnen sind.

**Comment by binderth** [comment]
Ja klar! Zu kompliziert gedacht!
Hast recht!
