### ISSUE TITLE
Adding a new entry to the phonebook - works sometimes only

### ISSUE THREAD

**Issue by bufemc** [blacksenator/fbcallrouter#4]
In der Datei x_contact.php gibt es die Methode setPhonebookEntry..

Ich habe versuchsweise und ganz absichtlich in der "beruehmten" true Loop ganz zu Anfang und absichtlich zweimal hinzugefuegt:

```
        $callrouter->setContact("TESTCASE2", "0099123456", 'RING', $blacklist);
        $callrouter->setContact("TESTCASE2", "0099123456", 'RING', $blacklist);
        die("DEBUG");
```

Das Ergebnis war, dass es "meist" mit dem Hinzufuegen ging, sobald ich aber zB einen Debugger einsetze und in setPhonebookEntry einen Breakpoint setze, sehe ich doch oefter dass das $result null ist, oder aber es wird zB nur einer der beiden Eintraege gesetzt (so hatte ich nach 3 Aufrufen teils statt 6 Eintraege 5 im Telefonbuch). 

Besonders krass: teilweise, also nur manchmal, bekomme ich geworfen HTTP unauthorized!

Dabei liegt das nicht am verwendeten Benutzer. Wenn es klappte, dann sowohl mit dslf_config als auch einem dediziert neuen Benutzer mit entsprechenden Rechten.

Ich wollte das nur auch nochmal dokumentiert haben. PR erstelle ich bislang keinen, da der Autor wahrscheinlich tiefer in der Materie drinsteckt, und ich mich erst einarbeiten muesste ;)

**Comment by blacksenator** [comment]
fixed with v2.2
