### ISSUE TITLE
extension=sockets have to be enabled in php.ini

### ISSUE THREAD

**Issue by bufemc** [blacksenator/fbcallrouter#5]
The config style has changed, tz ,) But that's not what this issue is about:
 
I got an exception that socket_import_stream would be unknown.. I googled the solution, it's easy to solve: you have to uncomment the line sockets in the php.ini file:

`extension=sockets`

Maybe just upgrade the README to mention this?

BTW, will have a long running test on W10 today and check if the problem with the silent socket is really fixed. ETA of result maybe 8:00 pm, after swimming.

PS: sockets war also bei mir bislang auskommentiert - frag mich nicht warum dann andere socket-Funktionen trotzdem taten. Ist sicher wieder sowas Unergruendliches meiner Lieblingshasssprache ,)

**Comment by bufemc** [comment]
Unfortunately the socket is still "dead" under Windows, after a while. I started it 13:43 and provoked a call, worked fine for both, fbcallrouter and my Python solution. Then at about 19:34 I called again (really ~2 minutes before "socket refresh"), but this time the event is not recorded for fbcallrouter. So issue https://github.com/blacksenator/fbcallrouter/issues/3 seems to be still a thing.

26.06.2020 13:43:14 => CALL IN from number 01755290xxx to MSN 732xxx
26.06.2020 13:43:15 => Caller has a rating of 5 and 0 comments.
26.06.2020 13:43:17 => DISCONNECT
26.06.2020 15:36:39 => Status: Regular Socket refresh
26.06.2020 17:36:40 => Status: Regular Socket refresh
**-- the call event is missing here --**
26.06.2020 19:36:41 => Status: Regular Socket refresh

As indirectly said, my Python solution did receive the call event. I even stopped it and called again, so it's not a "who comes first" thing, here it's log:

26.06.20 13:43:16;RING;0;01755290xxx;732xxx;SIP1;
26.06.20 13:43:19;DISCONNECT;0;0;
26.06.20 19:34:38;RING;0;01755290xxx;732xxx;SIP1;
26.06.20 19:34:44;DISCONNECT;0;0;

I even called after the "socket refresh" from 19:36:41 - but.. nothing.

**Comment by blacksenator** [comment]
@bufemc 
After the various changes, the program on the RaspberryPi runs continuously without any problems. The socket is continuously renewed. Apart from that, I can't find a solution for a Windows installation.

**Comment by bufemc** [comment]
If s.o. should use this under Windows, and the "socket died quietly" thingy is still a problem: this was a far from perfect, but a working workaround for me: just re-build the socket connection each 80th run:

```
    $fbSocket = false; // will be initialised below
    $counter = 0;
    while (true) {

        if ($counter % 80 == 0) {
            $fbSocket = $callrouter->getSocket();
            stream_set_timeout ($fbSocket, 1);        
        }     
        $counter += 1;

       [hier der bisherige Code der Loop]
    }
```
