### ISSUE TITLE
I want to install this on a Raspberry Zero W and can't get any further

### ISSUE THREAD

**Issue by hem0773** [blacksenator/fbcallrouter#8]
Hello !
I want to install this on a Raspberry Zero W and can't get any further

`pi@raspberrypi:~/fbcallrouter $ php fbcallrouter run
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /home/pi/fbcallrouter/fbcallrouter:10
Stack trace:
#0 {main}
  thrown in /home/pi/fbcallrouter/fbcallrouter on line 10
pi@raspberrypi:~/fbcallrouter $
`

**Comment by blacksenator** [comment]
Looks like you've forgotten to install composer or haven't install the necessary libraries

`composer install --no-dev --no-suggest`

**Comment by hem0773** [comment]
Good morning !
Yes, I had already done it again

![grafik](https://user-images.githubusercontent.com/57199067/137620453-45cda033-0245-4028-8a78-91e941308aca.png)

**Comment by blacksenator** [comment]
Please take a close look at the messages: it says that the **composer.json** file cannot be found. Please change to the directory  `/fbcallrouter` and execute the composer command again.

**Comment by hem0773** [comment]
![grafik](https://user-images.githubusercontent.com/57199067/137622459-5c136ef9-e7be-4d1d-aca5-6c2fd0e53838.png)

**Comment by blacksenator** [comment]
Please take a close look at the messages: it says that php modules are missing. Please check your PHP installation.

**Comment by hem0773** [comment]
I had almost thought of PHP

I only had
sudo apt-get install php

executed and I didn't worry about php-cli, php-curl, php-mbstring, php-soap, php-xml

now it works thanks
