### ISSUE TITLE
Warum gesperrt

### ISSUE THREAD

**Issue by hem0773** [blacksenator/fbcallrouter#9]
12.09.2022 14:00:55 => Status: Regular Socket refresh
12.09.2022 14:02:45 => CALL IN from number 01517082XXXX to MSN 68XX
12.09.2022 14:02:45 => The caller is using an illegal subscriber number! Added $
12.09.2022 14:03:32 => DISCONNECT

Warum wird die Nummer gesperrt
Danke

**Comment by blacksenator** [comment]
Hallo,
danke für den Hinweis. Hier liegt tatsächlich ein Fehler vor.
Die Rufnummer wird darauf geprüft, ob sie nach der Vorwahl mit einer Null ('0') beginnt. Dies ist für Festnetznummern nicht zulässig und zeigt, das ein Spammer eine Fake-Nummer übermittelt. Bei Mobilrufnummern ist dies erlaubt und sollte daher vom Programm eigentlich auch entsprechend berücksichtigt werden. Die Abfrage dazu war aber nicht präziese genug programmiert.
Korrektur erfolgt umgehend.
